version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    container_name: telamentis-neo4j
    environment:
      - NEO4J_AUTH=neo4j/telamentis123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"    # HTTP
      - "7687:7687"    # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - telamentis

  telamentis-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telamentis-core
    environment:
      - RUST_LOG=info
      - TELAMENTIS_NEO4J_URL=bolt://neo4j:7687
      - TELAMENTIS_NEO4J_USER=neo4j
      - TELAMENTIS_NEO4J_PASSWORD=telamentis123
    depends_on:
      - neo4j
    ports:
      - "3000:3000"    # Core service port
    networks:
      - telamentis

  fastapi:
    build:
      context: ./presentation/fastapi-bridge
      dockerfile: Dockerfile
    container_name: telamentis-fastapi
    environment:
      - TELAMENTIS_CORE_URL=http://telamentis-core:3000
    depends_on:
      - telamentis-core
    ports:
      - "8000:8000"    # FastAPI HTTP port
    networks:
      - telamentis

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  telamentis:
    driver: bridge